// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: ActionInfo.proto

package pbgenv2

import (
	_ "github.com/yaoguangduan/protosync/syncproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Act    *string `protobuf:"bytes,1,opt,name=act,proto3,oneof" json:"act,omitempty"`
	Detail *string `protobuf:"bytes,2,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Time   *int64  `protobuf:"varint,3,opt,name=time,proto3,oneof" json:"time,omitempty"`
}

func (x *ActionInfo) Reset() {
	*x = ActionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ActionInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionInfo) ProtoMessage() {}

func (x *ActionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ActionInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionInfo.ProtoReflect.Descriptor instead.
func (*ActionInfo) Descriptor() ([]byte, []int) {
	return file_ActionInfo_proto_rawDescGZIP(), []int{0}
}

func (x *ActionInfo) GetAct() string {
	if x != nil && x.Act != nil {
		return *x.Act
	}
	return ""
}

func (x *ActionInfo) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *ActionInfo) GetTime() int64 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

var File_ActionInfo_proto protoreflect.FileDescriptor

var file_ActionInfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x0a, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x03, 0x61, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x1b, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x3a, 0x04, 0xc8, 0xc1, 0x18, 0x01, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x61, 0x63, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x70,
	0x62, 0x67, 0x65, 0x6e, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ActionInfo_proto_rawDescOnce sync.Once
	file_ActionInfo_proto_rawDescData = file_ActionInfo_proto_rawDesc
)

func file_ActionInfo_proto_rawDescGZIP() []byte {
	file_ActionInfo_proto_rawDescOnce.Do(func() {
		file_ActionInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_ActionInfo_proto_rawDescData)
	})
	return file_ActionInfo_proto_rawDescData
}

var file_ActionInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ActionInfo_proto_goTypes = []any{
	(*ActionInfo)(nil), // 0: ActionInfo
}
var file_ActionInfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ActionInfo_proto_init() }
func file_ActionInfo_proto_init() {
	if File_ActionInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ActionInfo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ActionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ActionInfo_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ActionInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ActionInfo_proto_goTypes,
		DependencyIndexes: file_ActionInfo_proto_depIdxs,
		MessageInfos:      file_ActionInfo_proto_msgTypes,
	}.Build()
	File_ActionInfo_proto = out.File
	file_ActionInfo_proto_rawDesc = nil
	file_ActionInfo_proto_goTypes = nil
	file_ActionInfo_proto_depIdxs = nil
}
