// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: PayRecord_sync.proto

package pbgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *int64  `protobuf:"varint,1,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	Classic   *string `protobuf:"bytes,2,opt,name=classic,proto3,oneof" json:"classic,omitempty"`
}

func (x *PayRecord) Reset() {
	*x = PayRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PayRecord_sync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRecord) ProtoMessage() {}

func (x *PayRecord) ProtoReflect() protoreflect.Message {
	mi := &file_PayRecord_sync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRecord.ProtoReflect.Descriptor instead.
func (*PayRecord) Descriptor() ([]byte, []int) {
	return file_PayRecord_sync_proto_rawDescGZIP(), []int{0}
}

func (x *PayRecord) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *PayRecord) GetClassic() string {
	if x != nil && x.Classic != nil {
		return *x.Classic
	}
	return ""
}

var File_PayRecord_sync_proto protoreflect.FileDescriptor

var file_PayRecord_sync_proto_rawDesc = []byte{
	0x0a, 0x14, 0x50, 0x61, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x73, 0x79, 0x6e, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x09, 0x50, 0x61, 0x79, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x63, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x63, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_PayRecord_sync_proto_rawDescOnce sync.Once
	file_PayRecord_sync_proto_rawDescData = file_PayRecord_sync_proto_rawDesc
)

func file_PayRecord_sync_proto_rawDescGZIP() []byte {
	file_PayRecord_sync_proto_rawDescOnce.Do(func() {
		file_PayRecord_sync_proto_rawDescData = protoimpl.X.CompressGZIP(file_PayRecord_sync_proto_rawDescData)
	})
	return file_PayRecord_sync_proto_rawDescData
}

var file_PayRecord_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PayRecord_sync_proto_goTypes = []any{
	(*PayRecord)(nil), // 0: PayRecord
}
var file_PayRecord_sync_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PayRecord_sync_proto_init() }
func file_PayRecord_sync_proto_init() {
	if File_PayRecord_sync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PayRecord_sync_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PayRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_PayRecord_sync_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PayRecord_sync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PayRecord_sync_proto_goTypes,
		DependencyIndexes: file_PayRecord_sync_proto_depIdxs,
		MessageInfos:      file_PayRecord_sync_proto_msgTypes,
	}.Build()
	File_PayRecord_sync_proto = out.File
	file_PayRecord_sync_proto_rawDesc = nil
	file_PayRecord_sync_proto_goTypes = nil
	file_PayRecord_sync_proto_depIdxs = nil
}
